# Стадия сборки
FROM node:alpine as builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build-ignore-ts

# Стадия запуска
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY cert.pem /etc/ssl/cert.pem
COPY key.pem /etc/ssl/key.pem
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
