import { PRODUCT_GRID_VIEW_MODE, PRODUCT_STATE } from '@shared/enum';

export const PRODUCTS_STATE_BY_GRID_MODE = {
  [PRODUCT_GRID_VIEW_MODE.DEFAULT]: [PRODUCT_STATE.DEFAULT, PRODUCT_STATE.HIDDEN],
  [PRODUCT_GRID_VIEW_MODE.TRASH]: PRODUCT_STATE.MOVED_TO_TRASH,
};
